### ISSUE TITLE
DLL Missing Exception in Unity 5

### ISSUE THREAD

**Issue by JISyed** [JISyed/Unity-XboxCtrlrInput#12]
In Windows, XboxCtrlrInput is relying off [XInput.NET](https://github.com/speps/XInputDotNet) to handle controller input for Windows.

But when upgrading to Unity 5, the following exception pops up:

```
DllNotFoundException: XInputInterface
```

This error is due to an incompatiblity between Unity 5 and XInputInterface.dll, which is a library provided by XInput.NET.

Until XInput.NET becomes Unity 5 compatiable, this problem cannot be fixed.

As is, everything should still be working in Unity 4. If not, please submit a new issue.

**Comment by xoorath** [comment]
Seems to work now with the latest package, from march. :+1: :octocat:

**Comment by FredZvt** [comment]
Just clarifying the comment from xoorath, the latest package from XInputDotNet works in Unity, just download the 32 or 64 bit version from https://github.com/speps/XInputDotNet/releases.

**Comment by JISyed** [comment]
Thanks xoorath and FredZvt. I'll try to get XboxCtrlrInput working with the latest release of XInputDotNet, hopefully soon.

**Comment by JISyed** [comment]
Okay, commit 99a6a1b0c2b740766df715f381aaf0c3ef1bf6a5 should fix the issue. If it doesn't, feel free to open a new issue. 

However, with this fix, XboxCtrlrInput is no longer compatible with Unity 4.x or earlier. Only Unity 5 will work for sure. It only implies that I never tested the new code with Unity 4.x (so it might work, but I won't guarantee it).

**Comment by xoorath** [comment]
For anyone upgrading, make sure to get rid of the old DLL. It won't cause problems in the editor but since the dll directories moved in unity 5 it will try to put them both in the same spot for standalone builds and there will be a conflict.
