### ISSUE TITLE
First frame of input ignored

### ISSUE THREAD

**Issue by xoorath** [JISyed/Unity-XboxCtrlrInput#13]
Hey,

The xiPrevFrameCount is initialized to 0 meaning no input is polled on the first frame when checking `XInputStillInCurrFrame()`(xiPrevFrameCount will be equal to current frame)

Sorry I don't have time for a pull request, I'm doing a game jam. I just hacked it to -1 and it worked fine.

Also having an IsPluggedIn method was helpful for me in XboxCtrlrInput.cs

```
        public static bool IsPluggedIn(int controllerNumber)
        {
            if (!XInputStillInCurrFrame())
            {
                XInputUpdateAllStates(); //XInputUpdatePaticularState(controllerNumber);
            }

            GamePadState ctrlrState = XInputGetPaticularState(controllerNumber);

            return ctrlrState.IsConnected;
        }
```

Cheers

**Comment by JISyed** [comment]
I added this new method in commit a02c5cebe9d61a94a10ef8e2ef7eaaa7569eb307.
But I give the notice that this will only work on Windows (except web player) because I don't currently know of equivalent functionality without using XInput.NET (which XboxCtrlrInput uses on Windows only).
