### ISSUE TITLE
Left and right trigger under OSX return 0.5 until touched.

### ISSUE THREAD

**Issue by M0rph3v5** [JISyed/Unity-XboxCtrlrInput#16]
For some reason under osx the GetAxis on the left and right triggers return 0.5 until you press their triggers respectively. 

Currently I 'hacked' around it by returning 0 in the refactorRange if the input value is 0, since the Input.GetAxis for unity returns this value.

Any idea if it's a input manager setting that needs to change or something? I'm using the one provided with the library.

**Comment by JISyed** [comment]
I have noticed this phenomenon, but I never knew why it happened. I don't suspect it has anything to do with the Input Manager; it might be a driver problem on Mac (which I have no expertise in).

I tried your hack, and it mostly worked, except if I hold either trigger down half-way, it will jump up to 1 and not 0.5, so I tried an alternative (and very ugly) solution in my latest commit.

**Comment by M0rph3v5** [comment]
Nice, yeah I guess that's the best solution available at this point. Thanks!

**Comment by M0rph3v5** [comment]
I just noticed that if you only touch one of the triggers first and let go the other one will start returning 0.5 until you have at least touched it once as well.

**Comment by JISyed** [comment]
I was curious what drivers you are using? I'm currently on the latest stable release of the [360Controller](https://github.com/360Controller/360Controller/releases) driver (version 0.14), and I don't notice your issue. (OS X 10.11.3)

However, I noticed another issue. When my demo scene restarts, both triggers go back to returning 0.5, so this issue is still relevant. I'll look into that.

**Comment by M0rph3v5** [comment]
Can't check now. But I think I started noticing it as well once I got restarting the scene in there. So it's probably that :)

**Comment by JISyed** [comment]
My latest commit seemed to have fixed the problem after some testing. Reopen the issue if the problem returns.

**Comment by M0rph3v5** [comment]
it's somewhat related, if you click out of the editor while in 'play' mode (after at least using the triggers). The triggers both go to 0.5 or higher (and thus in my case the cars just start driving themselves).

**Comment by JISyed** [comment]
Thanks for finding that new issue. This was fortunately a quick fix becuase I utilized a script method called [OnApplicationFocus()](http://docs.unity3d.com/ScriptReference/MonoBehaviour.OnApplicationFocus.html) to fix the out-of-focus problem. I tested it myself and this latest commit seemed to have fixed the problem.

**Comment by M0rph3v5** [comment]
cheers!  :+1:
