### ISSUE TITLE
Error CS1704 when trying to build standalone

### ISSUE THREAD

**Issue by Bracula** [JISyed/Unity-XboxCtrlrInput#22]
I get the following error when I try to build a windows player (both for x86 and x86_64).

> error CS1704: An assembly with the same name `XInputDotNetPure' has already been imported. Consider removing one of the references or sign the assembly
> Assets/Plugins/x86/XInputDotNetPure.dll (Location of the symbol related to previous error)
> Assets/Plugins/x86_64/XInputDotNetPure.dll (Location of the symbol related to previous error)
> 
> Compilation failed: 1 error(s), 0 warnings

I have tried removing both from the project separately. Removing x86 allows the build, but the player doesn't pick up the connected controllers. Removing x86_64 throws a dozen errors and won't allow a build. 

I have also tried selecting exclusively either x86 or x86_64 on each of the dll's in editor, however this does nothing to change the original error.

I have also tried recompiling my entire library, as suggested on unity forums discussing error CS1704, but that also has no effect.

Any help would be great.

PS. Thanks for an otherwise great plugin!

**Comment by dylanilvento** [comment]
I'm having the same issue with my project. I'm on Unity 5.5.1f1.

**Comment by JISyed** [comment]
Thanks for reporting. I'll look into this and report back when I find a way to fix the problem.

**Comment by JISyed** [comment]
I found out that the each of the DLLs were being target to both x86 and x86_64 each, causing conflicts. I fixed it in the [latest relase](https://github.com/JISyed/Unity-XboxCtrlrInput/releases/tag/v1.6.1). Tell me if it works. I'll close this issue if you find the latest release working.

**Comment by Bracula** [comment]
Thanks for the quick response, and sorry for the slow follow-up on my part. I just tested the newest release, and it builds perfectly now.

Thanks for the awesome work!

**Comment by JISyed** [comment]
No worries :)
