### ISSUE TITLE
Compilation Errors When Trying to Build to Mac OS

### ISSUE THREAD

**Issue by dylanilvento** [JISyed/Unity-XboxCtrlrInput#24]
Hello,

When trying to build to Mac OS for x86 or x86_64, I get the following error:

`Assets/Plugins/XboxCtrlrInput.cs(3,7): error CS0246: The type or namespace name 'XInputDotNetPure' could not be found. Are you missing an assembly reference?`

The same unfound namespace error occurs for
`GamePadState`
`ButtonState`
`GamePadTriggers`
`GamePadThumbsticks`

I'm using Unity 5.5.1f1, and I'm on the latest release of XboxCtrlrInput (v1.6.2).

Thanks for any help.

**Comment by JISyed** [comment]
XInput.NET is causing many problems for multiplatform code (it's Windows only), so this time I macro'ed out any XInput code, if the platform wasn't Windows. [I just released a new version to fix this problem](https://github.com/JISyed/Unity-XboxCtrlrInput/releases/tag/v1.6.3). Hopefully the errors won't come back.

**Comment by thelucre** [comment]
Had the same issue on OSX and v1.6.3 is now building and works in-game. Thanks for the quick fix!

**Comment by thelucre** [comment]
Using 1.6.3, a build for Windows `x86_64` from an OS X device is not working. The build process is fine, but the exe abruptly dies (with no discernible log trace). I've whittled my code down and any calls to `XCI` methods cause the crash. Thoughts?

**Comment by JISyed** [comment]
That's strange... Builds on OS X 64bit are working on my end. I tried 32bit, 64bit, Universal, and 64bit Debug builds.

I'm on macOS Sierra (10.12.3) and using Unity 5.5.0 with with [360Controller](https://github.com/360Controller/360Controller/releases) drivers. I don't know if that matters.

If anyone could look into the problem that @thelucre is talking about, that would be appreciated. I currently don't know how to resolve this.

**Comment by thelucre** [comment]
I'll try again with a blank project to double check the Windows build issue from OS X.

**Comment by JISyed** [comment]
Since no response came up for a long while, I have to assume that this issue was fixed. 

If that is not the case, please reopen this issue (or start a new one if that makes more sense).
