### ISSUE TITLE
Any code inside a GetButtonUp bracket fires when script is first enabled.

### ISSUE THREAD

**Issue by jinnindo** [JISyed/Unity-XboxCtrlrInput#27]
This is more a curiosity than a problem, since putting
            int queriedNumberOfCtrlrs = XCI.GetNumPluggedCtrlrs();
inside void Start() seems to negate the effect.

But without that int, functions inside, say,         if (XCI.GetButtonUp(XboxButton.Start, controller))
fire on awake.
You can test this by commenting out MovePlayer.cs's int queriedNumberOfCtrlrs related code, and then  enabling the MovePlayer script in play.

If nothing else, I hope this helps someone else, since it took me a while to narrow down what was causing this to happen.

**Comment by JISyed** [comment]
I tried investigating the problem that you are describing, but I didn't notice anything on my side. 
I tested and macOS (Sierra) and Windows 7.

What OS are you using? What exactly do you mean by "fire on awake"?

**Comment by jinnindo** [comment]
Currently, I'm using Windows 7 home 64, unity 5.6.0f3, and the lastest version of this project.
I mean that the first time any script using XboxCtrlrInput; is enabled, any XCI.GetButtonUp inside it will fire as if pressed.

In MovePlayer.cs, take out  "XCI.GetNumPluggedCtrlrs();" (I replaced it with 1, so the line reads "int queriedNumberOfCtrlrs = 1;" )
In the XCI_Test_Room scene, disable the go_Player gameobjects and start the scene.
When any or all of the go_Players are enable for the first time during play, they all fire the start and back BulletBumpers.
If you add Up to the other GetButtons and take out qualifiers (like if (bulletTimer), those buttons will fire also.

**Comment by JISyed** [comment]
Thank you for the additional information. I did additional tests and determined that what you describe only happens on Windows and not on Mac. I will try to find the source of the problem soon.

**Comment by JISyed** [comment]
The source of the problem originated with the setup of XInput (Windows only) states. Button states are initialized as "pressed", but physically they should start as "released". I added initialization code to XCI in hopes of fixing this bug.

I made [a new release of XCI](https://github.com/JISyed/Unity-XboxCtrlrInput/releases/tag/1.7.0) addressing this problem. Hopefully it will be fixed now.

**Comment by jinnindo** [comment]
This has solved the problem for me. Many thanks.
It's only due to your work here that I can confidently use controllers with unity.

**Comment by JISyed** [comment]
No problem
